name: Run Tests

on:
  push:
    branches:
      - Test1
  pull_request:
    branches:
      - main
      - Test1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate
          python -m pip install --upgrade pip
          pip install flask flask-cors flask-bcrypt flask-jwt-extended pymongo pytest

      - name: Run tests
        run: |
          source myenv/bin/activate
          pytest tests/test_app.py
